<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.22000.0</TargetPlatformMinVersion>
    <RootNamespace>AttaquerTaskbar</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">win-x64</RuntimeIdentifier>
    <Platforms>x64;ARM64</Platforms>
    <UseWinUI>true</UseWinUI>
    <WinUISDKReferences>false</WinUISDKReferences>
    <EnableMsixTooling>true</EnableMsixTooling>
    <DefaultLanguage>en-US</DefaultLanguage>
    <AppxPackageSigningEnabled>true</AppxPackageSigningEnabled>
    <GenerateAppInstallerFile>false</GenerateAppInstallerFile>
    <GenerateTestArtifacts>false</GenerateTestArtifacts>
    <AppxBundle>Never</AppxBundle>
    <AppxBundlePlatforms>x64</AppxBundlePlatforms>
    <PublishAot>true</PublishAot>
    <DefineConstants>$(DefineConstants);DISABLE_XAML_GENERATED_MAIN</DefineConstants>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Version>0.1.0</Version>
    <ApplicationIcon>Assets\Icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Icon.ico" />
    <Content Include="Assets\Square44x44Logo.png" />
    <Content Include="Assets\Square150x150Logo.png" />
    <Content Include="Assets\StoreLogo.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Deskband11Lib.WinUI" Version="1.4.2" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2526" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.4.0" />
    <PackageReference Include="WinUIEx" Version="2.9.3" />
  </ItemGroup>
</Project>
